input: 0  # 0-camera, 1-video, 2-image

car_engine_file: "./src/main/detection/models/ignore/car_11s.engine"
armor_engine_file: "./src/main/detection/models/ignore/armor_11s.engine"

camera_config_file: "./src/main/camera/camera_io/configs/camera.yaml"
video_path: "/home/radar/Videos/vlc-record-2026-01-24-17h52m03s-2025-08-02_16-32-19.mp4-.mp4"
image_path: "./src/main/camera/images/your_image.jpg"

