#-------------------------------------attention-----------------------------------------------
enemy: "red"
# enemy: "blue"
#-------------------------------------attention-----------------------------------------------
sigma_q_x: 50.0
sigma_q_y: 50.0
sigma_r_x: 0.1
sigma_r_y: 0.1

# DISTANCE_THRESHOLD: 1.0
# TIME_THRESHOLD: 1.5